name: integration-tests

on:
  push:
    branches:
      - master

jobs:
  integration-test-python:
    runs-on: ubuntu-latest
    container: python:3.7
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Install dependencies
        run: make install-python-ci-dependencies
      - name: Test python
        run: FEAST_TELEMETRY=False pytest --verbose --color=yes sdk/python/tests --integration
        env:
          REDIS_TYPE: REDIS
          REDIS_CONNECTION_STRING: redis:6379,db=0
